networks:
  eon-network:
    external: true

volumes:
  eon-volume:
    driver: local

services:
  # create docker compose for database
  database:
    image: postgres:14
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 'acessoAdmin@2024'
      POSTGRES_DB: postgres
    volumes:
      - ./Database/GenerateDatabase.sql:/docker-entrypoint-initdb.d/GenerateDatabase.sql
      - eon-volume:/var/lib/postgresql/data
    networks:
      - eon-network

  # create docker compose for pgadmin
  pgadmin:
    image: dpage/pgadmin4:7.5
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@eon.com.br'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    networks:
      - eon-network
    depends_on:
      - database
